name: komiut_app
description: A new Flutter project.
publish_to: "none"
version: 1.2.2+5

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  google_fonts: 6.1.0
  flutter_animate: ^4.5.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
